name: CI

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Install SFML library
              run: |
                sudo apt update
                sudo apt install -y libsfml-dev

            - name: Build C++ code
              run: |
                mkdir build
                cd build
                cmake ..
                make